name: Thuban CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Toolchain
        compile: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib mtools binutils nasm

      - name: Compile Kernel
        compile: make run

      - name: Check Artifacts
        compile: |
          if [ ! -f "build/thuban.bin" ]; then
            echo "Kernel binary not found!"
            exit 1
          fi
